version: '3.9'

services:
  my-app: 
    image: 559050223633.dkr.ecr.ap-south-1.amazonaws.com/my-app:1.0
    ports: 
      - 5000:5000
    depends_on:
      - db
    environment:
      # These environment variables will help your app connect to the database
      DATABASE_URL: "postgresql://postgres:123456@db:5432/postgres"
      # Or if your app uses individual variables:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: 123456
      DB_NAME: postgres

  db:
    image: postgres
    restart: always
    shm_size: 128mb
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080  # Changed to the correct Adminer port

volumes:
  postgres_data:  # This will persist your database data